#!/bin/bash

# Script tested for OSX only.

function checkFFMPEG {
    if [ ! -f bin/ffmpeg ]; then
        echo "Extracting FFMPEG..."
        open bin/ffmpeg-2.0.7z;
    fi
}

function checkBrew {
    local isInstalled="1"
    command -v brew>/dev/null 2>&1 || { isInstalled="0"; }
    
    if [ "isInstalled" = "0" ];
    then ruby <(curl -fsSkL raw.github.com/mxcl/homebrew/go);
    fi
}

function checkNodeJS {
    command -v node >/dev/null 2>&1 || {
        echo >&2 "Installing NodeJS...";
        checkBrew
        brew install node
        exit 1;
    }
}

function checkYTDL {
    command -v ytdl >/dev/null 2>&1 || {
        echo >&2 "Installing YTDL...";
        npm install -g ytdl
        npm install -g oauth
        exit 1;
    }
}

while test $# -gt 0; do
    case "$1" in
        ffmpeg)
            checkFFMPEG;
            checkNodeJS;
            checkYTDL;
                        
            exit 0;
            ;;
        
        *)
            break
            ;;
    esac
done
