#!/bin/bash

function checkAndInstallBrew {
    local isInstalled="1"
    brew -v foo>/dev/null 2>&1 || { isInstalled="0"; }
    
    if [ "isInstalled" = "0" ];
    then ruby <(curl -fsSkL raw.github.com/mxcl/homebrew/go);
    #else echo "brew already installed.";
    fi
}

function installLibAACPlus {
    echo "Installing FFMPEG dependency : libaacplus ...";

    wget http://217.20.164.161/~tipok/aacplus/libaacplus-2.0.2.tar.gz
    tar xzf libaacplus-2.0.2.tar.gz
    cd libaacplus-2.0.2
    # libtool on osx is quite different from the gnu libtool, which is called glibtool on osx
    sed -i '.bck' -e 's/libtool/glibtool/' autogen.sh
    ./autogen.sh
    make && make install
    cd ..
}

function installFFMPEG {
    checkAndInstallBrew;
    echo "Installing FFMPEG...";
    # from http://ffmpeg.org/trac/ffmpeg/wiki/MacOSXCompilationGuide
    
    echo "Installing FFMPEG dependencies...";
    brew install automake celt faac fdk-aac git lame libass libtool libvorbis libvpx \
    libvo-aacenc opencore-amr openjpeg opus sdl schroedinger shtool speex texi2html \
    theora wget x264 xvid yasm;
    
    echo "Compiling FFMPEG...";
    if [ ! -d "ffmpeg"]; then 
    git clone git://source.ffmpeg.org/ffmpeg.git ffmpeg
    cd ffmpeg
    ./configure --enable-gpl --enable-version3 --enable-nonfree --enable-postproc --enable-libaacplus \
    --enable-libass --enable-libcelt --enable-libfaac --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame \
    --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-openssl \
    --enable-libopus --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libvo-aacenc \
    --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --prefix=/usr/local
    make && make install
    cd ..
    
    exit 0;
}


while test $# -gt 0; do
    case "$1" in
        ffmpeg)
            ffmpeg -v foo>/dev/null 2>&1 || { installFFMPEG; exit 1; }
            ;;
        
        *)
            break
            ;;
    esac
done
